global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape Ray's metrics export endpoint (default port 8080 on each node)
  - job_name: "ray"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8080"]
