"""
Create Triton config.pbtxt files for each model.

This script generates config files with dynamic batching enabled.
"""

from pathlib import Path


def create_config(model_name: str, model_dir: Path):
    """Create config.pbtxt for a model."""

    config_content = f'''# Triton Configuration for {model_name}
# Auto-generated by create_triton_configs.py

name: "{model_name}"
backend: "pytorch"
max_batch_size: 32

# ============================================================================
# DYNAMIC BATCHING CONFIGURATION
# ============================================================================
# This is the KEY feature for learning AI infrastructure patterns!
#
# Dynamic batching accumulates multiple inference requests into a single batch
# before executing on the GPU/CPU. This dramatically improves throughput.
#
# Example with max_queue_delay=5ms and max_batch_size=32:
# - Request 1 arrives at t=0ms
# - Triton waits up to 5ms for more requests
# - Requests 2-10 arrive at t=2ms
# - At t=5ms (timeout), Triton executes batch of 10 requests
# - Result: 10x throughput improvement vs. processing individually
# ============================================================================

dynamic_batching {{
  # Wait up to 5ms to accumulate more requests into the batch
  # Trade-off: Lower = less latency, smaller batches
  #           Higher = more latency, larger batches, better throughput
  max_queue_delay_microseconds: 5000

  # Preferred batch sizes (powers of 2 are most efficient on GPUs)
  # Triton will try to create batches of these sizes when possible
  preferred_batch_size: [4, 8, 16, 32]

  # Don't preserve ordering for better throughput
  preserve_ordering: false
}}

# ============================================================================
# INPUT TENSORS
# ============================================================================

input [
  {{
    name: "user_ids"
    data_type: TYPE_INT64
    dims: [-1]  # Dynamic dimension, actual shape: [batch_size]
  }},
  {{
    name: "item_ids"
    data_type: TYPE_INT64
    dims: [-1]  # Dynamic dimension, actual shape: [batch_size]
  }}
]

# ============================================================================
# OUTPUT TENSORS
# ============================================================================

output [
  {{
    name: "scores"
    data_type: TYPE_FP32
    dims: [1]  # Shape: [batch_size, 1]
  }}
]

# ============================================================================
# INSTANCE CONFIGURATION
# ============================================================================
# Run on CPU (no GPU available in this setup)
# For GPU deployment, change KIND_CPU to KIND_GPU

instance_group [
  {{
    count: 1
    kind: KIND_CPU
  }}
]

# ============================================================================
# VERSION POLICY
# ============================================================================
# Serve only the latest version

version_policy: {{
  latest: {{
    num_versions: 1
  }}
}}
'''

    config_path = model_dir / "config.pbtxt"
    config_path.write_text(config_content)
    print(f"✓ Created config for {model_name} at {config_path}")


def main():
    """Create config files for all models."""

    triton_models_dir = Path(__file__).parent.parent / "triton" / "models"

    print("=" * 60)
    print("Creating Triton Config Files")
    print("=" * 60)

    models = ["recommendation_v1", "recommendation_v2"]

    for model_name in models:
        model_dir = triton_models_dir / model_name
        if model_dir.exists():
            create_config(model_name, model_dir)
        else:
            print(f"⚠ Model directory not found: {model_dir}")
            print(f"  Run generate_models.py first to create the models")

    print("\n" + "=" * 60)
    print("✓ Config creation complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
